### ISSUE TITLE
Error when validating Bulk

### ISSUE THREAD

**Issue by DanielMaimba** [StrategicDimensions/inuka#36]
When I click on the Validate button on a bulk and the bulk has more than one sales order and more than one delivery order, we get a singleton error as below:

Odoo Server Error
Traceback (most recent call last):
  File "/home/odoo/src/odoo/odoo/http.py", line 646, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/home/odoo/src/odoo/odoo/http.py", line 307, in _handle_exception
    raise pycompat.reraise(type(exception), exception, sys.exc_info()[2])
  File "/home/odoo/src/odoo/odoo/tools/pycompat.py", line 87, in reraise
    raise value
  File "/home/odoo/src/odoo/odoo/http.py", line 683, in dispatch
    result = self._call_function(**self.params)
  File "/home/odoo/src/odoo/odoo/http.py", line 339, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/home/odoo/src/odoo/odoo/service/model.py", line 97, in wrapper
    return f(dbname, *args, **kwargs)
  File "/home/odoo/src/odoo/odoo/http.py", line 332, in checked_call
    result = self.endpoint(*a, **kw)
  File "/home/odoo/src/odoo/odoo/http.py", line 927, in __call__
    return self.method(*args, **kw)
  File "/home/odoo/src/odoo/odoo/http.py", line 512, in response_wrap
    response = f(*args, **kw)
  File "/home/odoo/src/odoo/addons/web/controllers/main.py", line 928, in call_button
    action = self._call_kw(model, method, args, {})
  File "/home/odoo/src/odoo/addons/web/controllers/main.py", line 916, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/home/odoo/src/odoo/odoo/api.py", line 689, in call_kw
    return call_kw_multi(method, model, args, kwargs)
  File "/home/odoo/src/odoo/odoo/api.py", line 680, in call_kw_multi
    result = method(recs, *args, **kwargs)
  File "/home/odoo/src/user/inuka/models/bulk_master.py", line 154, in button_validate
    pickings.with_context(from_bulk=True).button_validate()
  File "/home/odoo/src/user/inuka/models/stock.py", line 63, in button_validate
    return super(Picking, self).button_validate()
  File "/home/odoo/src/odoo/addons/stock/models/stock_picking.py", line 647, in button_validate
    self.ensure_one()
  File "/home/odoo/src/odoo/odoo/models.py", line 4265, in ensure_one
    raise ValueError("Expected singleton: %s" % self)
ValueError: Expected singleton: stock.picking(5, 6)

**Comment by mdi-odoo** [comment]
Thanks for reporting. Fixed at revision: https://github.com/StrategicDimensions/inuka/commit/0212875253fa5f05744579e05708b3b1df35977b .
