### ISSUE TITLE
Error when Trying to upgrade the INUKA App

### ISSUE THREAD

**Issue by DanielMaimba** [StrategicDimensions/inuka#44]
When trying to upgrade the INUKA App, we are getting the following error:
![image](https://user-images.githubusercontent.com/14073662/34822939-3f602a34-f6d1-11e7-9c49-72d099faae41.png)

Odoo Server Error

Traceback (most recent call last):
  File "/home/odoo/src/odoo/odoo/models.py", line 967, in _validate_fields
    check(self)
  File "/home/odoo/src/odoo/odoo/addons/base/ir/ir_ui_view.py", line 338, in _check_xml
    self.postprocess_and_fields(view.model, view_doc, view.id)
  File "/home/odoo/src/odoo/odoo/addons/base/ir/ir_ui_view.py", line 1024, in postprocess_and_fields
    self.raise_view_error("\n".join(msg_lines), view_id)
  File "/home/odoo/src/odoo/odoo/addons/base/ir/ir_ui_view.py", line 506, in raise_view_error
    raise ValueError(message)
ValueError: Field 'watchlist' used in attributes must be present in view but is missing:
 - 'watchlist' in attrs="{'invisible':['|',('watchlist', '=', False),('customer', '=', False)]}"
 - 'watchlist' in attrs="{'invisible':['|',('watchlist', '=', True),('customer', '=', False)]}"

Error context:
View `res.partner.form.inherit.inuka`
[view_id: 1684, xml_id: n/a, model: res.partner, parent_id: 112]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/odoo/src/odoo/odoo/tools/convert.py", line 741, in parse
    self._tags[rec.tag](rec, de, mode=mode)
  File "/home/odoo/src/odoo/odoo/tools/convert.py", line 651, in _tag_record
    id = self.env(context=rec_context)['ir.model.data']._update(rec_model, self.module, res, rec_id or False, not self.isnoupdate(data_node), noupdate=self.isnoupdate(data_node), mode=self.mode)
  File "/home/odoo/src/odoo/odoo/addons/base/ir/ir_model.py", line 1469, in _update
    record = record.create(values)
  File "/home/odoo/src/enterprise/web_studio/models/studio_mixin.py", line 18, in create
    res = super(StudioMixin, self).create(vals)
  File "/home/odoo/src/odoo/odoo/addons/base/ir/ir_ui_view.py", line 401, in create
    return super(View, self).create(self._compute_defaults(values))
  File "/home/odoo/src/odoo/odoo/models.py", line 3286, in create
    self._fields[key].determine_inverse(record)
  File "/home/odoo/src/odoo/odoo/fields.py", line 1078, in determine_inverse
    getattr(records, self.inverse)()
  File "/home/odoo/src/odoo/odoo/addons/base/ir/ir_ui_view.py", line 269, in _inverse_arch
    view.write(data)
  File "/home/odoo/src/enterprise/web_studio/models/studio_mixin.py", line 27, in write
    res = super(StudioMixin, self).write(vals)
  File "/home/odoo/src/odoo/odoo/addons/base/ir/ir_ui_view.py", line 417, in write
    return super(View, self).write(self._compute_defaults(vals))
  File "/home/odoo/src/odoo/odoo/models.py", line 3008, in write
    self._write(old_vals)
  File "/home/odoo/src/odoo/odoo/models.py", line 3161, in _write
    self._validate_fields(vals)
  File "/home/odoo/src/odoo/odoo/models.py", line 971, in _validate_fields
    raise ValidationError("%s\n\n%s" % (_("Error while validating constraint"), tools.ustr(e)))
odoo.exceptions.ValidationError: ('Error while validating constraint\n\nField \'watchlist\' used in attributes must be present in view but is missing:\n - \'watchlist\' in attrs="{\'invisible\':[\'|\',(\'watchlist\', \'=\', False),(\'customer\', \'=\', False)]}"\n - \'watchlist\' in attrs="{\'invisible\':[\'|\',(\'watchlist\', \'=\', True),(\'customer\', \'=\', False)]}"\n\nError context:\nView `res.partner.form.inherit.inuka`\n[view_id: 1684, xml_id: n/a, model: res.partner, parent_id: 112]', None)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/odoo/src/odoo/odoo/http.py", line 646, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/home/odoo/src/odoo/odoo/http.py", line 307, in _handle_exception
    raise pycompat.reraise(type(exception), exception, sys.exc_info()[2])
  File "/home/odoo/src/odoo/odoo/tools/pycompat.py", line 87, in reraise
    raise value
  File "/home/odoo/src/odoo/odoo/http.py", line 683, in dispatch
    result = self._call_function(**self.params)
  File "/home/odoo/src/odoo/odoo/http.py", line 339, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/home/odoo/src/odoo/odoo/service/model.py", line 97, in wrapper
    return f(dbname, *args, **kwargs)
  File "/home/odoo/src/odoo/odoo/http.py", line 332, in checked_call
    result = self.endpoint(*a, **kw)
  File "/home/odoo/src/odoo/odoo/http.py", line 927, in __call__
    return self.method(*args, **kw)
  File "/home/odoo/src/odoo/odoo/http.py", line 512, in response_wrap
    response = f(*args, **kw)
  File "/home/odoo/src/odoo/addons/web/controllers/main.py", line 928, in call_button
    action = self._call_kw(model, method, args, {})
  File "/home/odoo/src/odoo/addons/web/controllers/main.py", line 916, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/home/odoo/src/odoo/odoo/api.py", line 689, in call_kw
    return call_kw_multi(method, model, args, kwargs)
  File "/home/odoo/src/odoo/odoo/api.py", line 680, in call_kw_multi
    result = method(recs, *args, **kwargs)
  File "<decorator-gen-45>", line 2, in button_immediate_upgrade
  File "/home/odoo/src/odoo/odoo/addons/base/module/module.py", line 71, in check_and_log
    return method(self, *args, **kwargs)
  File "/home/odoo/src/odoo/odoo/addons/base/module/module.py", line 602, in button_immediate_upgrade
    return self._button_immediate_function(type(self).button_upgrade)
  File "/home/odoo/src/odoo/odoo/addons/base/module/module.py", line 541, in _button_immediate_function
    modules.registry.Registry.new(self._cr.dbname, update_module=True)
  File "/home/odoo/src/odoo/odoo/modules/registry.py", line 85, in new
    odoo.modules.load_modules(registry._db, force_demo, status, update_module)
  File "/home/odoo/src/odoo/odoo/modules/loading.py", line 339, in load_modules
    force, status, report, loaded_modules, update_module)
  File "/home/odoo/src/odoo/odoo/modules/loading.py", line 242, in load_marked_modules
    loaded, processed = load_module_graph(cr, graph, progressdict, report=report, skip_modules=loaded_modules, perform_checks=perform_checks)
  File "/home/odoo/src/odoo/odoo/modules/loading.py", line 156, in load_module_graph
    _load_data(cr, module_name, idref, mode, kind='data')
  File "/home/odoo/src/odoo/odoo/modules/loading.py", line 94, in _load_data
    tools.convert_file(cr, module_name, filename, idref, mode, noupdate, kind, report)
  File "/home/odoo/src/odoo/odoo/tools/convert.py", line 788, in convert_file
    convert_xml_import(cr, module, fp, idref, mode, noupdate, report)
  File "/home/odoo/src/odoo/odoo/tools/convert.py", line 849, in convert_xml_import
    obj.parse(doc.getroot(), mode=mode)
  File "/home/odoo/src/odoo/odoo/tools/convert.py", line 748, in parse
    exc_info[2]
  File "/home/odoo/src/odoo/odoo/tools/pycompat.py", line 86, in reraise
    raise value.with_traceback(tb)
  File "/home/odoo/src/odoo/odoo/tools/convert.py", line 741, in parse
    self._tags[rec.tag](rec, de, mode=mode)
  File "/home/odoo/src/odoo/odoo/tools/convert.py", line 651, in _tag_record
    id = self.env(context=rec_context)['ir.model.data']._update(rec_model, self.module, res, rec_id or False, not self.isnoupdate(data_node), noupdate=self.isnoupdate(data_node), mode=self.mode)
  File "/home/odoo/src/odoo/odoo/addons/base/ir/ir_model.py", line 1469, in _update
    record = record.create(values)
  File "/home/odoo/src/enterprise/web_studio/models/studio_mixin.py", line 18, in create
    res = super(StudioMixin, self).create(vals)
  File "/home/odoo/src/odoo/odoo/addons/base/ir/ir_ui_view.py", line 401, in create
    return super(View, self).create(self._compute_defaults(values))
  File "/home/odoo/src/odoo/odoo/models.py", line 3286, in create
    self._fields[key].determine_inverse(record)
  File "/home/odoo/src/odoo/odoo/fields.py", line 1078, in determine_inverse
    getattr(records, self.inverse)()
  File "/home/odoo/src/odoo/odoo/addons/base/ir/ir_ui_view.py", line 269, in _inverse_arch
    view.write(data)
  File "/home/odoo/src/enterprise/web_studio/models/studio_mixin.py", line 27, in write
    res = super(StudioMixin, self).write(vals)
  File "/home/odoo/src/odoo/odoo/addons/base/ir/ir_ui_view.py", line 417, in write
    return super(View, self).write(self._compute_defaults(vals))
  File "/home/odoo/src/odoo/odoo/models.py", line 3008, in write
    self._write(old_vals)
  File "/home/odoo/src/odoo/odoo/models.py", line 3161, in _write
    self._validate_fields(vals)
  File "/home/odoo/src/odoo/odoo/models.py", line 971, in _validate_fields
    raise ValidationError("%s\n\n%s" % (_("Error while validating constraint"), tools.ustr(e)))
odoo.tools.convert.ParseError: "Error while validating constraint

Field 'watchlist' used in attributes must be present in view but is missing:
 - 'watchlist' in attrs="{'invisible':['|',('watchlist', '=', False),('customer', '=', False)]}"
 - 'watchlist' in attrs="{'invisible':['|',('watchlist', '=', True),('customer', '=', False)]}"

Error context:
View `res.partner.form.inherit.inuka`
[view_id: 1684, xml_id: n/a, model: res.partner, parent_id: 112]
None" while parsing /home/odoo/src/user/inuka/views/res_partner_views.xml:4, near
<record id="view_res_partner_form_inherit_inuka" model="ir.ui.view">
        <field name="name">res.partner.form.inherit.inuka</field>
        <field name="model">res.partner</field>
        <field name="inherit_id" ref="base.view_partner_form"/>
        <field name="arch" type="xml">
            <data><xpath expr="//sheet" position="before">
                <header>
                    <button name="action_watchlist_add" type="object" string="Add Watchlist" attrs="{'invisible':['|',('watchlist', '=', True),('customer', '=', False)]}" class="btn-primary"/>
                    <button name="action_watchlist_remove" type="object" string="Remove Watchlist" attrs="{'invisible':['|',('watchlist', '=', False),('customer', '=', False)]}" class="btn-primary"/>
                    <field name="status" widget="statusbar" statusbar_visible="candidate,new,junior,senior,pearl,ruby,emerald,sapphire,diamond,double_diamond,triple_diamond,exective_diamond,presidential" attrs="{'invisible':[('customer', '=', False)]}"/>
                </header>
            </xpath>
            <field name="user_id" position="attributes">
                <attribute name="string">Mentor</attribute>
            </field>
            <field name="type" position="before">
                <field name="first_name" attrs="{'invisible': [('customer', '=', False)], 'required': [('customer', '=', True)]}"/>
                <field name="passport_no" attrs="{'invisible': [('customer', '=', False)], 'required': [('customer', '=', True)]}"/>
                <field name="join_date" attrs="{'invisible': [('customer', '=', False)]}"/>
                <field name="dob" attrs="{'invisible': [('customer', '=', False)]}"/>
                <field name="is_admin" invisible="1"/>
            </field>
            <field name="function" position="before">
                <field name="last_name" attrs="{'invisible': [('customer', '=', False)], 'required': [('customer', '=', True)]}"/>
            </field>
            <field name="lang" position="before">
                <field name="home_phone" widget="phone" attrs="{'invisible': [('customer', '=', False)]}"/>
            </field>
            <field name="lang" position="after">
                <field name="upline" domain="[('customer', '=', True)]" attrs="{'invisible': [('customer', '=', False)], 'required': [('customer', '=', True)]}"/>
                <field name="upline_id" attrs="{'invisible': [('customer', '=', False)], 'required': [('customer', '=', True)]}"/>
            </field>
            <field name="vat" position="replace"/>
            <field name="function" position="replace"/>
            <field name="website" position="replace"/>
            <field name="ref" position="replace">
                <field name="ref" attrs="{'readonly': [('is_admin', '=', False), ('customer', '=', True)]}"/>
            </field>
        </data></field>
    </record>

**Comment by mdi-odoo** [comment]
Fixed in revision: https://github.com/StrategicDimensions/inuka/commit/fdb1b46fe7fea778720e823fe101bb43009f4bf2
