### ISSUE TITLE
Error when you Run Birthday Helpdesk Ticket scheduled action

### ISSUE THREAD

**Issue by DanielMaimba** [StrategicDimensions/inuka#47]
When you run the Birthday Helpdesk Ticket scheduled action by clicking Run Manually the following error is happening:

I also see that this condition was not met (The cron should search all customer where:
Day & Month of the DOB field on the customer record = Day & Month from {TOMORROW’s DATE})

Odoo Server Error

Traceback (most recent call last):
  File "/home/odoo/src/odoo/odoo/tools/safe_eval.py", line 348, in safe_eval
    return unsafe_eval(c, globals_dict, locals_dict)
  File "", line 1, in <module>
  File "/home/odoo/src/user/inuka/models/partner.py", line 695, in create_birthday_ticket
    ticket.message_subscribe(channel_ids=[channel.id])
  File "/home/odoo/src/odoo/addons/mail/models/mail_thread.py", line 2010, in message_subscribe
    self.sudo().write({'message_follower_ids': gen})
  File "/home/odoo/src/enterprise/helpdesk/models/helpdesk_ticket.py", line 263, in write
    res = super(HelpdeskTicket, self - assigned_tickets - closed_tickets).write(vals)
  File "/home/odoo/src/odoo/addons/mail/models/mail_thread.py", line 277, in write
    result = super(MailThread, self).write(values)
  File "/home/odoo/src/odoo/addons/rating/models/rating.py", line 165, in write
    result = super(RatingMixin, self).write(values)
  File "/home/odoo/src/odoo/odoo/models.py", line 3008, in write
    self._write(old_vals)
  File "/home/odoo/src/odoo/odoo/models.py", line 3133, in _write
    field.write(self.with_context(rel_context), vals[name])
  File "/home/odoo/src/odoo/odoo/fields.py", line 2261, in write
    comodel.create(act[2])
  File "/home/odoo/src/odoo/addons/mail/models/mail_followers.py", line 126, in create
    res = super(Followers, self).create(vals)
  File "/home/odoo/src/odoo/odoo/models.py", line 3278, in create
    record = self.browse(self._create(old_vals))
  File "/home/odoo/src/odoo/odoo/models.py", line 3371, in _create
    cr.execute(query, tuple(u[2] for u in updates if len(u) > 2))
  File "/home/odoo/src/odoo/odoo/sql_db.py", line 155, in wrapper
    return f(self, *args, **kwargs)
  File "/home/odoo/src/odoo/odoo/sql_db.py", line 232, in execute
    res = self._obj.execute(query, params)
psycopg2.IntegrityError: new row for relation "mail_followers" violates check constraint "mail_followers_partner_xor_channel"
DETAIL:  Failing row contains (66139, helpdesk.ticket, 1, null, null).

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/odoo/src/odoo/odoo/http.py", line 646, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/home/odoo/src/odoo/odoo/http.py", line 307, in _handle_exception
    raise pycompat.reraise(type(exception), exception, sys.exc_info()[2])
  File "/home/odoo/src/odoo/odoo/tools/pycompat.py", line 87, in reraise
    raise value
  File "/home/odoo/src/odoo/odoo/http.py", line 683, in dispatch
    result = self._call_function(**self.params)
  File "/home/odoo/src/odoo/odoo/http.py", line 339, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/home/odoo/src/odoo/odoo/service/model.py", line 97, in wrapper
    return f(dbname, *args, **kwargs)
  File "/home/odoo/src/odoo/odoo/http.py", line 332, in checked_call
    result = self.endpoint(*a, **kw)
  File "/home/odoo/src/odoo/odoo/http.py", line 927, in __call__
    return self.method(*args, **kw)
  File "/home/odoo/src/odoo/odoo/http.py", line 512, in response_wrap
    response = f(*args, **kw)
  File "/home/odoo/src/odoo/addons/web/controllers/main.py", line 934, in call_button
    action = self._call_kw(model, method, args, {})
  File "/home/odoo/src/odoo/addons/web/controllers/main.py", line 922, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/home/odoo/src/odoo/odoo/api.py", line 689, in call_kw
    return call_kw_multi(method, model, args, kwargs)
  File "/home/odoo/src/odoo/odoo/api.py", line 680, in call_kw_multi
    result = method(recs, *args, **kwargs)
  File "/home/odoo/src/odoo/odoo/addons/base/ir/ir_cron.py", line 75, in method_direct_trigger
    self.sudo(user=cron.user_id.id).ir_actions_server_id.run()
  File "/home/odoo/src/odoo/odoo/addons/base/ir/ir_actions.py", line 541, in run
    res = func(action, eval_context=eval_context)
  File "/home/odoo/src/odoo/addons/website/models/ir_actions.py", line 57, in run_action_code_multi
    res = super(ServerAction, self).run_action_code_multi(action, eval_context)
  File "/home/odoo/src/odoo/odoo/addons/base/ir/ir_actions.py", line 417, in run_action_code_multi
    safe_eval(action.sudo().code.strip(), eval_context, mode="exec", nocopy=True)  # nocopy allows to return 'action'
  File "/home/odoo/src/odoo/odoo/tools/safe_eval.py", line 371, in safe_eval
    pycompat.reraise(ValueError, ValueError('%s: "%s" while evaluating\n%r' % (ustr(type(e)), ustr(e), expr)), exc_info[2])
  File "/home/odoo/src/odoo/odoo/tools/pycompat.py", line 86, in reraise
    raise value.with_traceback(tb)
  File "/home/odoo/src/odoo/odoo/tools/safe_eval.py", line 348, in safe_eval
    return unsafe_eval(c, globals_dict, locals_dict)
  File "", line 1, in <module>
  File "/home/odoo/src/user/inuka/models/partner.py", line 695, in create_birthday_ticket
    ticket.message_subscribe(channel_ids=[channel.id])
  File "/home/odoo/src/odoo/addons/mail/models/mail_thread.py", line 2010, in message_subscribe
    self.sudo().write({'message_follower_ids': gen})
  File "/home/odoo/src/enterprise/helpdesk/models/helpdesk_ticket.py", line 263, in write
    res = super(HelpdeskTicket, self - assigned_tickets - closed_tickets).write(vals)
  File "/home/odoo/src/odoo/addons/mail/models/mail_thread.py", line 277, in write
    result = super(MailThread, self).write(values)
  File "/home/odoo/src/odoo/addons/rating/models/rating.py", line 165, in write
    result = super(RatingMixin, self).write(values)
  File "/home/odoo/src/odoo/odoo/models.py", line 3008, in write
    self._write(old_vals)
  File "/home/odoo/src/odoo/odoo/models.py", line 3133, in _write
    field.write(self.with_context(rel_context), vals[name])
  File "/home/odoo/src/odoo/odoo/fields.py", line 2261, in write
    comodel.create(act[2])
  File "/home/odoo/src/odoo/addons/mail/models/mail_followers.py", line 126, in create
    res = super(Followers, self).create(vals)
  File "/home/odoo/src/odoo/odoo/models.py", line 3278, in create
    record = self.browse(self._create(old_vals))
  File "/home/odoo/src/odoo/odoo/models.py", line 3371, in _create
    cr.execute(query, tuple(u[2] for u in updates if len(u) > 2))
  File "/home/odoo/src/odoo/odoo/sql_db.py", line 155, in wrapper
    return f(self, *args, **kwargs)
  File "/home/odoo/src/odoo/odoo/sql_db.py", line 232, in execute
    res = self._obj.execute(query, params)
ValueError: <class 'psycopg2.IntegrityError'>: "new row for relation "mail_followers" violates check constraint "mail_followers_partner_xor_channel"
DETAIL:  Failing row contains (66139, helpdesk.ticket, 1, null, null).
" while evaluating
'model.create_birthday_ticket()'

**Comment by mdi-odoo** [comment]
Fixed in revision: https://github.com/StrategicDimensions/inuka/commit/a09e8204093923cb1d077143554864f38eea3c43 .
