### ISSUE TITLE
URGENT: Internal Server Error when accessing inuka-dedicated.odoo.com

### ISSUE THREAD

**Issue by DanielMaimba** [StrategicDimensions/inuka#53]
Applied the latest code to Inuka-Dedicated and now when you access it we are getting an internal server error.

When you check the logs, this is the error that I can see. Please review asap

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "/home/odoo/src/odoo/odoo/http.py", line 115, in dispatch_rpc
result = dispatch(method, params)
File "/home/odoo/src/odoo/odoo/service/model.py", line 39, in dispatch
res = fn(db, uid, *params)
File "/home/odoo/src/odoo/odoo/service/model.py", line 153, in execute_kw
return execute(db, uid, obj, method, *args, **kw or {})
File "/home/odoo/src/odoo/odoo/service/model.py", line 97, in wrapper
return f(dbname, *args, **kwargs)
File "/home/odoo/src/odoo/odoo/service/model.py", line 160, in execute
res = execute_cr(cr, uid, obj, method, *args, **kw)
File "/home/odoo/src/odoo/odoo/service/model.py", line 149, in execute_cr
return odoo.api.call_kw(recs, method, args, kw)
File "/home/odoo/src/odoo/odoo/api.py", line 689, in call_kw
return call_kw_multi(method, model, args, kwargs)
File "/home/odoo/src/odoo/odoo/api.py", line 680, in call_kw_multi
result = method(recs, *args, **kwargs)
File "/home/odoo/src/odoo/odoo/addons/base/res/res_partner.py", line 514, in write
result = result and super(Partner, self).write(vals)
File "/home/odoo/src/odoo/addons/mail/models/mail_thread.py", line 265, in write
track_self = self.with_context(lang=self.env.user.lang)
File "/home/odoo/src/odoo/odoo/fields.py", line 951, in __get__
self.determine_value(record)
File "/home/odoo/src/odoo/odoo/fields.py", line 1062, in determine_value
self.compute_value(recs)
File "/home/odoo/src/odoo/odoo/fields.py", line 1018, in compute_value
self._compute_value(records)
File "/home/odoo/src/odoo/odoo/fields.py", line 1011, in _compute_value
self.compute(records)
File "/home/odoo/src/odoo/odoo/fields.py", line 599, in _compute_related
record[self.name] = value[self.related_field.name]
File "/home/odoo/src/odoo/odoo/models.py", line 4659, in __getitem__
return self._fields[key].__get__(self, type(self))
File "/home/odoo/src/odoo/odoo/fields.py", line 951, in __get__
self.determine_value(record)
File "/home/odoo/src/odoo/odoo/fields.py", line 1052, in determine_value
record._prefetch_field(self)
File "/home/odoo/src/odoo/odoo/models.py", line 2565, in _prefetch_field
result = records.read([f.name for f in fs], load='_classic_write')
File "/home/odoo/src/odoo/odoo/models.py", line 2509, in read
self._read_from_database(stored, inherited)
File "/home/odoo/src/odoo/odoo/models.py", line 2628, in _read_from_database
cr.execute(query_str, params)
File "/home/odoo/src/odoo/odoo/sql_db.py", line 155, in wrapper
return f(self, *args, **kwargs)
File "/home/odoo/src/odoo/odoo/sql_db.py", line 232, in execute
res = self._obj.execute(query, params)
psycopg2.ProgrammingError: column res_partner.is_top_level_member does not exist
LINE 1: ...rtner"."o_personal_pv_ytd" as "o_personal_pv_ytd","res_partn...
^

**Comment by mdi-odoo** [comment]
I don't see this is due to code. But you need to update the database.
