### ISSUE TITLE
Internal Server Error on SMS Reply Callback

### ISSUE THREAD

**Issue by DanielMaimba** [StrategicDimensions/inuka#67]
When the SMS reply callback url is called there is an internal server error received, you can test it by running the following URL: https://inuka-dedicated.odoo.com/sms/reply?api_id=3536578&from=27798802470&to=34055&timestamp=2018-02-15%2005:45:05&text=&keyword=@inuka

2018-02-15 15:05:03,601 4 INFO strategicdimensions-inuka-data-migration-master-22212 werkzeug: 196.192.186.18 - - [15/Feb/2018 15:05:03] "GET /sms/reply?api_id=3536578&from=27798802470&to=34055×tamp=2018-02-15%2005:45:05&text=&keyword=@inuka HTTP/1.1" 500 -
2018-02-15 15:05:03,605 4 ERROR strategicdimensions-inuka-data-migration-master-22212 werkzeug: Error on request:
Traceback (most recent call last):
File "/usr/local/lib/python3.5/dist-packages/werkzeug/serving.py", line 270, in run_wsgi
execute(self.server.app)
File "/usr/local/lib/python3.5/dist-packages/werkzeug/serving.py", line 258, in execute
application_iter = app(environ, start_response)
File "/home/odoo/src/odoo/odoo/service/server.py", line 252, in app
return self.app(e, s)
File "/home/odoo/src/odoo/odoo/service/wsgi_server.py", line 164, in application
return werkzeug.contrib.fixers.ProxyFix(application_unproxied)(environ, start_response)
File "/usr/local/lib/python3.5/dist-packages/werkzeug/contrib/fixers.py", line 152, in __call__
return self.app(environ, start_response)
File "/home/odoo/src/odoo/odoo/service/wsgi_server.py", line 154, in application_unproxied
result = handler(environ, start_response)
File "/home/odoo/src/odoo/odoo/http.py", line 1306, in __call__
return self.dispatch(environ, start_response)
File "/home/odoo/src/odoo/odoo/http.py", line 1269, in __call__
return self.app(environ, start_wrapped)
File "/usr/local/lib/python3.5/dist-packages/werkzeug/wsgi.py", line 766, in __call__
return self.app(environ, start_response)
File "/home/odoo/src/odoo/odoo/http.py", line 1470, in dispatch
result = ir_http._dispatch()
File "/home/odoo/src/odoo/addons/website_sale/models/ir_http.py", line 15, in _dispatch
return super(IrHttp, cls)._dispatch()
File "/home/odoo/src/odoo/addons/auth_signup/models/ir_http.py", line 19, in _dispatch
return super(Http, cls)._dispatch()
File "/home/odoo/src/odoo/addons/web_editor/models/ir_http.py", line 21, in _dispatch
return super(IrHttp, cls)._dispatch()
File "/home/odoo/src/odoo/addons/http_routing/models/ir_http.py", line 391, in _dispatch
result = super(IrHttp, cls)._dispatch()
File "/home/odoo/src/odoo/addons/utm/models/ir_http.py", line 20, in _dispatch
response = super(IrHttp, cls)._dispatch()
File "/home/odoo/src/odoo/odoo/addons/base/ir/ir_http.py", line 212, in _dispatch
return cls._handle_exception(e)
File "/home/odoo/src/odoo/addons/website/models/ir_http.py", line 164, in _handle_exception
return super(Http, cls)._handle_exception(exception)
File "/home/odoo/src/odoo/odoo/addons/base/ir/ir_http.py", line 182, in _handle_exception
return request._handle_exception(exception)
File "/home/odoo/src/odoo/odoo/http.py", line 761, in _handle_exception
return super(HttpRequest, self)._handle_exception(exception)
File "/home/odoo/src/odoo/odoo/http.py", line 307, in _handle_exception
raise pycompat.reraise(type(exception), exception, sys.exc_info()[2])
File "/home/odoo/src/odoo/odoo/tools/pycompat.py", line 87, in reraise
raise value
File "/home/odoo/src/odoo/odoo/addons/base/ir/ir_http.py", line 208, in _dispatch
result = request.dispatch()
File "/home/odoo/src/odoo/odoo/http.py", line 820, in dispatch
r = self._call_function(**self.params)
File "/home/odoo/src/odoo/odoo/http.py", line 339, in _call_function
return checked_call(self.db, *args, **kwargs)
File "/home/odoo/src/odoo/odoo/service/model.py", line 97, in wrapper
return f(dbname, *args, **kwargs)
File "/home/odoo/src/odoo/odoo/http.py", line 332, in checked_call
result = self.endpoint(*a, **kw)
File "/home/odoo/src/odoo/odoo/http.py", line 927, in __call__
return self.method(*args, **kw)
File "/home/odoo/src/odoo/odoo/http.py", line 512, in response_wrap
response = f(*args, **kw)
File "/home/odoo/src/user/inuka_sms/controllers/main.py", line 30, in sms_reply_notification
helpdesk_ticket = request.env['helpdesk.ticket'].sudo().search([('partner_id', '=', partner.id), ('create_date','>=', (fields.Datetime.context_today(self)-relativedelta(day=1)).strftime('%%Y-%%m-%%d'))], limit=1, order="create_date desc")
NameError: name 'fields' is not defined

**Comment by mdi-odoo** [comment]
Fixed in revision: https://github.com/StrategicDimensions/inuka/commit/746c9474bfdad41d2f5d340dbcb7ca7f30b6ff22
